name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    # 3つのOSに対してジョブを行う
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v3

      # CMakeでビルドディレクトリを生成（configure）
      - name: Configure
        run: cmake -B build

      # ターゲット(check)をビルド・実行
      - name: Build and Run Check
        run: cmake --build build --target check
